### ISSUE TITLE
Enable HTTPS on fsharp.org

### ISSUE THREAD

**Issue by haf** [fsharp/fsfoundation#489]
It would be great to enable HTTPS for fsharp.org, because the internet is under attack and people who use HTTP get exploited to a lesser or greater extent. We want people to trust F# and for that we need to build technological solutions that are trust-worthy.

Since github pages don't seem to support HTTPS for custom domains, we should find a solution that allows us to host/specify a HTTP certificate on our own. Some alternatives:
- self-host on DigitalOcean
- Heroku with custom certificate

Suave could be used to serve the contents from a static directory and if we do Heroku we can probably outsource the build-server sort of activity to them. Otherwise, you can do `bundle exec jekyll && rsync site@fsharp.org:/var/www/` if you have deploy-access, or a CI server could do it.

**Comment by tpetricek** [comment]
It would be great if we could add HTTPS support.

Just to add a bit of a background - at the moment, the setup is that GitHub automatically invokes Jekyll when someone commits a change and then hosts the produced files. This is something that would be really nice to keep because it means that changing the web site is just a matter of clicking "Accept PR" button :-).

This makes the situation a bit tricky, because we need to run this transformation somewhere - a CI could probably do this for us - or I suppose we could run write a script that runs this during the installation (AFAIK Heroku & Azure certainly have a way to do this).

**Comment by haf** [comment]
Also, for reference, I have a working ruby installation running DotNetZip so that any merged PR to master with a new semver causes a new release to be made using the secrets supports on AppVeyor. https://github.com/haf/DotNetZip.Semverd/blob/master/appveyor.yml

**Comment by ReedCopsey** [comment]
This is now done natively via Github pages. I've done the required work to switch it over to https.
