### ISSUE TITLE
Speakers list never finishes loading

### ISSUE THREAD

**Issue by mathias-brandewinder** [fsharp/fsfoundation#711]
In the [speakers list](http://community.fsharp.org/speakers) page, the page never finishes loading and displaying the speakers.

**Comment by StachuDotNet** [comment]
This is due to not having an API key for the Google Maps call.
A few months back, the <script> started requiring a `?key` attribute, not currently supplied by the website.

It's generally ok to generate a key and use it in a public site (not a secret), as the end user can just look at the <script> tag anyway.

This is technically an issue in https://github.com/fsharp/community.fsharp.org so I'm going to create a new issue there. I'll reply later with the link to that issue, and then this one can be marked as 'complete' while the conclusion happens there.

**Comment by StachuDotNet** [comment]
Ping - this can be closed - resolved by @ReedCopsey in the above-referenced repo.
