### ISSUE TITLE
F# Dugnad Community Cleanup Session: 15 July 2020

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsfoundation#827]
Once a month @cartermp and @dsyme get together to "clean up the neighbourhood" of some core F# assets. It's the "Dugnad" concept inspired by @mathias-brandewinder 

Please join us!  Teams link will be shared here.  This will be a social, fun occasion where we hang out - drinks and jokes and friendship are welcome but the aim is also to make some progress.

The invitation an open one.  The aim will be to dive in and get stuff done rather than chat about what to do

Next session is Jul 15, 2020, 8pm UK time.  We'll do a social call on teams and get stuff done. Join us!

Here's a list of some of the things we like to do.

* Test, use, simplify and clean https://fsharp.org/

* Spring clean https://github.com/fsharp/fsfoundation/

* Spring clean https://github.com/fsharp/fslang-design/
    
* Spring clean https://github.com/fsharp/fslang-suggestions/
    
* Help community improve https://en.wikipedia.org/wiki/F_Sharp_(programming_language)

* Help community with https://github.com/fsharp/fssf-website

* Improve https://fsharp.org/learn/

* Help orient more traffic to the high quality https://dotnet.microsoft.com/languages/fsharp

* Spring clean in https://fsharp.github.io/FSharp.Data/

* Check google searches for "F#", and "Learn F#" and "F# Tutorial"

* Discuss multi-language aspects, e.g. Russian/German/Chinese/Korean F# Wikipedia pages

**Comment by StachuDotNet** [comment]
> Join us!

How? Is there a sign-up form somewhere that I missed?

**Comment by dsyme** [comment]
I'll advertise a teams or slack link here before it happens :)

**Comment by dsyme** [comment]
Teams link is in this gist here: https://gist.github.com/dsyme/f3f4ba7fdf00689d00becb60255dcc70

I put it in the gist to help avoid getting spamm'd

**Comment by dsyme** [comment]
https://teams.microsoft.com/l/meetup-join/19%3ameeting_MTlmNzU5ZmUtZTAyYi00MTFjLWFhMmYtY2JlMjczNzM2ODMx%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%22e374a10e-9340-46d0-a4be-5af5ac3602d5%22%7d

**Comment by TomKemperNL** [comment]
Did a bit of [cleaning](https://en.wikipedia.org/w/index.php?title=F_Sharp_(programming_language)&action=history) on the Wiki page:
- removing SharpDevelop, MonoDevelop, and other old tooling)
- added links to some popular projects (Fake, SAFE stack, Paket, Fable, etc)

Rerouted dead link http://fsharp.org/use/html5 to http://fsharp.org/use/web-apps/.
On that note:

The current links from Wikipedia to FSharp.org are:
http://fsharp.org/use/web-apps/
http://fsharp.org/use/gpu/, this one is dead, moved to web.archive.com. I have no idea whether it's still a relevant thing.
http://fsharp.org/specs/language-spec/index.html

If we think the Wiki-page is important, we should probably somehow mark these links in the fsharp.org site as used on wiki (so we can either quickly edit wikipedia, or redirect appropriately).

If anyone has an idea in mind of what an exemplary Wikipedia page for a programming language should look like, let me know!

**Comment by dsyme** [comment]
This is great, thank you!

> http://fsharp.org/use/gpu/, this one is dead, moved to web.archive.com. I have no idea whether it's still a relevant thing.

It's dead (since GPU support is typically incorporated into libraries these days).  Just remove it.

> If we think the Wiki-page is important, we should probably somehow mark these links in the fsharp.org site as used on wiki (so we can either quickly edit wikipedia, or redirect appropriately).

Yes, or we be more careful about using Jekyll `redirect-to` on the fsharp.org site

**Comment by cartermp** [comment]
Thanks @TomKemperNL, the wiki page is super important and a lot of people visit that site!

Since I work for Microsoft it's not considered good for me to adjust things, but I can make a few suggestions:

Versions Table:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/6309070/88934920-09a38600-d236-11ea-83a0-3be031be5094.png">

* Change .NET Core SDK version to just ".NET Core 2.1"
* Add same entry to F# 4.7, but change to just '.NET Core 3.1" (technically it was .NET core 3.0, but 3.1 is the LTS)

Language evolution:

"F# uses an open development and engineering process. " ==> "F# uses an open development and engineering process, with suggestions and associated discussion, designs, and development all occuring on GitHub."

* "suggestions and associated discussion" links here: https://github.com/fsharp/fslang-suggestions
* "designs" links here: https://github.com/fsharp/fslang-design
* "development" links here: https://github.com/dotnet/fsharp

Great improvements overall, liking how it's taking shape 🙂

**Comment by dsyme** [comment]
The next F# community dugnad cleanup session will be on 25th August, 8pm BST, see https://github.com/fsharp/fsfoundation/issues/840

See you there!
