### ISSUE TITLE
F# Compiler Community Session - F# Compiler Service - An Online Chat with Don, Vlad and Community

### ISSUE THREAD

**Issue by vzarytovskii** [fsharp/fsfoundation#855]
Hello everyone, this is an announcement for our 5th compiler community session.

**What:** F# Compiler Service - An Online Chat with Don, Vlad and the community.

**When:** Monday 11th of January 2021, 7pm GMT (UK time), 8pm CET (Central European Standard Time), 11am PT ([everytimezone.com)](https://everytimezone.com/s/f16d3efe).

**Topics for our fifth session:**

F# Compiler Service:
  - What is compiler service.
  - Compiler service public surface area.
  - What's next for it.

**Previous sessions can be found here:** [1](https://github.com/fsharp/fsfoundation/issues/845), [2](https://github.com/fsharp/fsfoundation/issues/846), [3](https://github.com/fsharp/fsfoundation/issues/847), [4](https://github.com/fsharp/fsfoundation/issues/852), or on [F# Software Foundation YouTube channel](https://www.youtube.com/channel/UCsi00IVEgPoK7HvcpWDeSxQ)

Teams meeting link for the session: https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTg4NDVmY2ItOTA4Yi00YmRhLTg1ZDUtMzVlZDVhYzZlNGFm%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%2297f10a8e-3843-4db7-8ef7-f449e82693d7%22%7d

**Update**: recording is available on FSSF YT channel: [https://youtu.be/17a3i8WBQpg](https://youtu.be/17a3i8WBQpg)

**Comment by dsyme** [comment]
Great! See you there Vlad!

**Comment by NatElkins** [comment]
@vzarytovskii Are you planning on uploading this session to YouTube soon as well?

**Comment by vzarytovskii** [comment]
> @vzarytovskii Are you planning on uploading this session to YouTube soon as well?
Sure, didn't have a chance to upload it yet, hope to do it by the end of the week.

**Comment by vzarytovskii** [comment]
The recording is available on FSSF YT channel: [https://youtu.be/17a3i8WBQpg](https://youtu.be/17a3i8WBQpg)

**Comment by nojaf** [comment]
Thanks Vlad for organizing this and putting the recording on YouTube. This was very interesting.
One question I had while watching this: what is the release schedule for the FCS NuGet package?

**Comment by dsyme** [comment]
cc @cartermp

**Comment by cartermp** [comment]
We don't have one figured out yet. History doesn't provide a good guide either, since releases could be days apart of several months apart. I think we'll want to consider the following:

* Release with a VS release (every few months). This would coincide with all active development and stabilization efforts we do in the VS tools. FCS is used directly by VS now as a project reference.
* Monthly check-in for a release. If no consumers ask for an update, then no update is released that month.
* One-off releases for urgent matters (e.g., 38.0.2 to unblock scripting in Ionide)
